# Generated by Django 3.2.20 on 2023-07-29 16:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_prometheus.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('customer_id', models.CharField(max_length=255)),
                ('subscription_id', models.CharField(max_length=255)),
                ('subscription_type', models.CharField(choices=[('starter', 'Starter'), ('basic', 'Basic'), ('growth', 'Growth'), ('ultimate', 'Ultimate')], default='starter', max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=(django_prometheus.models.ExportModelOperationsMixin('subscription'), models.Model),
        ),
        migrations.CreateModel(
            name='EmailAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255)),
                ('verify_key', models.CharField(default='90ePllF1671PeYXJHi1BJNfRlYUVCLBf', max_length=255)),
                ('verified', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now=True)),
                ('verification_sent', models.DateTimeField(null=True)),
                ('reset_key', models.CharField(default=None, max_length=255, null=True)),
                ('reset_sent', models.DateTimeField(null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'email address',
                'verbose_name_plural': 'email addresses',
                'unique_together': {('user', 'email')},
            },
            bases=(django_prometheus.models.ExportModelOperationsMixin('email_address'), models.Model),
        ),
    ]
