# Generated by Django 3.2.20 on 2023-07-30 19:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailaddress',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='emailaddress', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='emailaddress',
            name='verify_key',
            field=models.CharField(default='j4Gh2qwnlCKdWKcJKwNAHuJozvVJRhaF', max_length=255),
        ),
    ]
