# Generated by Django 3.2.20 on 2023-07-28 22:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_emailaddress_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailaddress',
            options={'verbose_name': 'email address', 'verbose_name_plural': 'email addresses'},
        ),
        migrations.AddField(
            model_name='emailaddress',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='emailaddress',
            name='verification_sent',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterUniqueTogether(
            name='emailaddress',
            unique_together={('user', 'email')},
        ),
    ]
