# Generated by Django 3.2.20 on 2023-07-30 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20230730_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailaddress',
            name='verify_key',
            field=models.CharField(default='M0JDDOBS5a8eTSYI5DdhZVsCKKedP2r6', max_length=255, null=True),
        ),
    ]
