# Generated by Django 3.2.20 on 2023-07-28 23:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20230728_2224'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailaddress',
            name='key',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
