# Generated by Django 3.2.20 on 2023-07-31 04:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0004_alter_emailaddress_verify_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailaddress',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='email_address', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='emailaddress',
            name='verify_key',
            field=models.CharField(default='4K4uD0BT2go37BmeaTYNKyQZyjoK0bEN', max_length=255, null=True),
        ),
    ]
