# Generated by Django 3.2.20 on 2023-07-29 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_emailtemplate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailTemplate',
        ),
    ]
