# Generated by Django 3.2.20 on 2023-08-03 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_emailaddress_verify_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailaddress',
            name='verify_key',
            field=models.CharField(default='1L3c3xsHinI2mPxSJemWOvGhGagStzzL', max_length=255, null=True),
        ),
    ]
