# Generated by Django 3.2.20 on 2023-08-11 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20230811_0540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailaddress',
            name='verify_key',
            field=models.CharField(default='mNMS9wWNLQ0JIQxc9DIwgSaw1cwDuEYZ', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='client_reference_id',
            field=models.CharField(default='lD33zSiRxrH3MGPoGtfNkMa14e3D1Kx2', max_length=255),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='subscription_type',
            field=models.CharField(choices=[('starter', 'Starter'), ('basic', 'Basic'), ('growth', 'Growth'), ('ultimate', 'Ultimate'), ('pending', 'Pending')], default='starter', max_length=255),
        ),
    ]
