# Generated by Django 3.2.20 on 2023-08-19 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20230819_0126'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='previous_subscription_type',
            field=models.CharField(choices=[('starter', 'Starter'), ('basic', 'Basic'), ('growth', 'Growth'), ('ultimate', 'Ultimate'), ('pending', 'Pending')], default='starter', max_length=255),
        ),
        migrations.AlterField(
            model_name='emailaddress',
            name='verify_key',
            field=models.CharField(default='c3NbXmHkFQicVG7oe9wmnIvTSmKiDKUd', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='client_reference_id',
            field=models.CharField(default='wGIxeiPAHWFKJDK0YQBng8ta52CeQhtI', max_length=255),
        ),
    ]
