# Generated by Django 3.2.20 on 2023-08-19 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20230819_0127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailaddress',
            name='verify_key',
            field=models.CharField(default='0TUJ1wUrSWQy3Fffr0cghGWayuR2J9pF', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='client_reference_id',
            field=models.CharField(default='OXS2v895S3YEoJiAXDSWKp1ms9avyZs8', max_length=255),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='customer_id',
            field=models.CharField(default='', max_length=255),
        ),
    ]
