# Generated by Django 3.2.20 on 2023-08-19 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20230819_0209'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='period_end',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='period_start',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='emailaddress',
            name='verify_key',
            field=models.CharField(default='ErwQYYdrAo8bcnhujIk4b1fNA8AF4krX', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='client_reference_id',
            field=models.CharField(default='BY3SCnE2IyScDgA382HZUnrt8kJddA7F', max_length=255),
        ),
    ]
