# Generated by Django 3.2.20 on 2023-08-20 22:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0013_auto_20230819_0228'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailaddress',
            name='billing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='emailaddress',
            name='primary',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='emailaddress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_addresses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='emailaddress',
            name='verify_key',
            field=models.CharField(default='sf3Bi9STL1rDls0ZJmDN30QTAAJOHJ4K', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='client_reference_id',
            field=models.CharField(default='9h1OJMg8oG0B9RYiiJL0bNQdlL1Fpcyf', max_length=255),
        ),
    ]
