# Generated by Django 3.2.20 on 2023-08-23 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20230823_0341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailaddress',
            name='primary',
        ),
        migrations.AlterField(
            model_name='emailaddress',
            name='verification_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='emailaddress',
            name='verify_key',
            field=models.CharField(blank=True, default='arkDHk5mpgdKEjVeIircV4oIsBoWLyyS', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='client_reference_id',
            field=models.CharField(default='1JGsfdkBXUHv1mSqspZtBIrG2r6Q4pCt', max_length=255),
        ),
    ]
