# Generated by Django 3.2.20 on 2023-08-24 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20230823_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailaddress',
            name='verify_key',
            field=models.CharField(blank=True, default='2lxzoCxoPmoE0EaOTiBYU4cTXdZLcEGX', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='client_reference_id',
            field=models.CharField(default='ruq6WuhQbfL4AoaEzaOEAvSdmg6voTlH', max_length=255),
        ),
    ]
