# Generated by Django 3.2.20 on 2023-08-24 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_auto_20230824_0409'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailaddress',
            options={'ordering': ['-created'], 'verbose_name': 'email address', 'verbose_name_plural': 'email addresses'},
        ),
    ]
