# Generated by Django 3.2.20 on 2024-01-26 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_alter_emailaddress_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='cancel_at',
            field=models.DateTimeField(blank=True, default=None),
        ),
    ]
