# Generated by Django 3.2.20 on 2024-01-26 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_alter_subscription_cancel_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='cancel_at',
            field=models.DateTimeField(blank=True),
        ),
    ]
