# Generated by Django 3.2.20 on 2024-01-27 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_alter_subscription_cancel_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='cancel_at',
            field=models.DateTimeField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='period_end',
            field=models.DateTimeField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='period_start',
            field=models.DateTimeField(blank=True, default=None),
        ),
    ]
