# Generated by Django 3.2.20 on 2024-01-27 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_auto_20240127_0032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='period_start',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
