# Generated by Django 3.2.20 on 2024-01-27 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_alter_subscription_period_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='cancel_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
