# Generated by Django 4.2.9 on 2024-02-08 08:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0025_alter_subscription_cancel_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailaddress',
            options={'ordering': ['-created'], 'verbose_name': 'email', 'verbose_name_plural': 'emails'},
        ),
        migrations.AlterField(
            model_name='emailaddress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='previous_subscription_type',
            field=models.CharField(choices=[('starter', 'Starter'), ('basic', 'Basic'), ('growth', 'Growth'), ('ultimate', 'Ultimate'), ('pending', 'Pending'), ('canceled', 'Canceled')], default='starter', max_length=255),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='subscription_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='subscription_type',
            field=models.CharField(choices=[('starter', 'Starter'), ('basic', 'Basic'), ('growth', 'Growth'), ('ultimate', 'Ultimate'), ('pending', 'Pending'), ('canceled', 'Canceled')], default='starter', max_length=255),
        ),
    ]
