version: "3.9"

services:
  scheduler-scan:
    build:
      context: ./scheduler-scan
    environment:
      DB_USER: ${DJANGO_USER}
      DB_PASSWORD: ${DJANGO_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_DATABASE: ${DJANGO_DATABASE}
    volumes:
      - ./scheduler-scan:/app
    labels:
      logging: "promtail"
      logging_jobname: "containerlogs"
    restart: unless-stopped

  scheduler-cleaner:
    build:
      context: ./scheduler-cleaner
    environment:
      DB_USER: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - ./scheduler-cleaner:/app
    labels:
      logging: "promtail"
      logging_jobname: "containerlogs"
    restart: unless-stopped

  mailer:
    build:
      context: ./mailer
    environment:
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_USER: ${SMTP_USER}
      SMTP_PASS: ${SMTP_PASS}
      TARGET_URL: ${TARGET_URL}
    volumes:
      - ./mailer:/app
    labels:
      logging: "promtail"
      logging_jobname: "containerlogs"
    restart: unless-stopped

  scanner:
    build:
      context: ./scanner
    environment:
      DB_USER: ${DJANGO_USER}
      DB_PASSWORD: ${DJANGO_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_DATABASE: ${DJANGO_DATABASE}
    volumes:
      - ./scanner:/app
    labels:
      logging: "promtail"
      logging_jobname: "containerlogs"
    restart: unless-stopped

  cleaner:
    build:
      context: ./cleaner
    environment:
      DB_USER: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - ./cleaner:/app
    labels:
      logging: "promtail"
      logging_jobname: "containerlogs"
    restart: unless-stopped

  redis:
    image: "redis:alpine"
    volumes:
      - redis_data:/data
    expose:
      - "6379"
    labels:
      logging: "promtail"
      logging_jobname: "containerlogs"
    restart: unless-stopped

  redis-commander:
    image: rediscommander/redis-commander:latest
    hostname: redis-commander
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "127.0.0.1:8081:8081"
    restart: unless-stopped

  db:
    image: mysql:latest
    volumes:
      - db_data:/var/lib/mysql
      - ./db/backup:/docker-entrypoint-initdb.d
    restart: unless-stopped
    expose:
      - "3306"
    ports:
      - "127.0.0.1:3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    labels:
      logging: "promtail"
      logging_jobname: "containerlogs"

  django:
    command: python manage.py runserver 0.0.0.0:8888
    build:
      context: ./django
      dockerfile: Dockerfile.development
    environment:
      DOMAIN_NAME: ${DOMAIN_NAME}
      TARGET_URL: ${TARGET_URL}
      DB_HOST: ${DB_HOST}
      MYSQL_PORT: ${MYSQL_PORT}
      DJANGO_DATABASE: ${DJANGO_DATABASE}
      DJANGO_USER: ${DJANGO_USER}
      DJANGO_PASSWORD: ${DJANGO_PASSWORD}
      STRIPE_PUBLISHABLE_KEY: ${STRIPE_PUBLISHABLE_KEY}
      STRIPE_SECRET_KEY: ${STRIPE_SECRET_KEY}
      STRIPE_WEBHOOK_SECRET: ${STRIPE_WEBHOOK_SECRET}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_DB: ${REDIS_DB}
      REDIS_USER: ${REDIS_USER}
      REDIS_PASS: ${REDIS_PASS}
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_USER: ${SMTP_USER}
      SMTP_PASS: ${SMTP_PASS}
    volumes:
      - ./django:/app
      - ./static:/app/static
    ports:
      - "127.0.0.1:8888:8888"
    expose:
      - "8888"
    depends_on:
      - db
    labels:
      logging: "promtail"
      logging_jobname: "containerlogs"
    restart: unless-stopped

  django-worker:
    command: python manage.py rqworker
    build:
      context: ./django
      dockerfile: Dockerfile.development
    environment:
      DOMAIN_NAME: ${DOMAIN_NAME}
      TARGET_URL: ${TARGET_URL}
      DB_HOST: ${DB_HOST}
      MYSQL_PORT: ${MYSQL_PORT}
      DJANGO_DATABASE: ${DJANGO_DATABASE}
      DJANGO_USER: ${DJANGO_USER}
      DJANGO_PASSWORD: ${DJANGO_PASSWORD}
      STRIPE_PUBLISHABLE_KEY: ${STRIPE_PUBLISHABLE_KEY}
      STRIPE_SECRET_KEY: ${STRIPE_SECRET_KEY}
      STRIPE_WEBHOOK_SECRET: ${STRIPE_WEBHOOK_SECRET}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_DB: ${REDIS_DB}
      REDIS_USER: ${REDIS_USER}
      REDIS_PASS: ${REDIS_PASS}
    volumes:
      - ./django:/app
    depends_on:
      - db
    labels:
      logging: "promtail"
      logging_jobname: "containerlogs"
    restart: unless-stopped

  wordpress:
    build:
      context: ./wordpress
    volumes:
      - ./wordpress/wp-config.php:/var/www/html/wp-config.php
      - ./wordpress/wp-content:/var/www/html/wp-content
    expose:
      - "80"
    ports:
      - "127.0.0.1:8000:80"
    environment:
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
      WORDPRESS_DEBUG: ${WORDPRESS_DEBUG}
      DOMAIN_NAME: ${DOMAIN_NAME}
      TARGET_URL: ${TARGET_URL}
    extra_hosts:
      - ${DOMAIN_NAME}:${PUBLIC_IP}
    depends_on:
      - db
      - redis
    labels:
      logging: "promtail"
      logging_jobname: "containerlogs"
    restart: unless-stopped

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "127.0.0.1:3000:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/usr/src/app
    expose:
      - "8080"
    environment:
      CHOKIDAR_USEPOLLING: 'true'
      DOMAIN_NAME: ${DOMAIN_NAME}
      TARGET_URL: ${TARGET_URL}
      STRIPE_PUBLISHABLE_KEY: ${STRIPE_PUBLISHABLE_KEY}
    labels:
      logging: "promtail"
      logging_jobname: "containerlogs"
    restart: unless-stopped

  nginx:
    build:
      context: ./nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf:/etc/nginx/conf.d
      - ./wordpress/wp-content:/var/www/html/wp-content
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
      - ./static:/static
      - ./frontend/node_modules:/node_modules
      # - nginx_data:/usr/local/openresty/nginx/logs
      # - geoupdate_data:/var/lib/GeoIP/
    ports:
      - "80:80"
      - "443:443"
    environment:
      DOMAIN_NAME: ${DOMAIN_NAME}
      DOLLAR: ${DOLLAR}
    restart: unless-stopped
    labels:
      logging: "promtail"
      logging_jobname: "containerlogs"
    command:
      [
        "/bin/sh",
        "-c",
        "echo hello world && envsubst < /etc/nginx/conf.d/certninja.conf.template > /etc/nginx/conf.d/certninja.conf && exec nginx -g 'daemon off;'"
      ]

  certbot:
    image: certbot/certbot:latest
    restart: unless-stopped
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    labels:
      logging: "promtail"
      logging_jobname: "containerlogs"
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

  prometheus:
    image: prom/prometheus:latest
    restart: unless-stopped
    volumes:
      - prometheus_data:/prometheus
      - ./prometheus/:/etc/prometheus/
    ports:
      - 127.0.0.1:9090:9090
    labels:
      logging: "promtail"
      logging_jobname: "containerlogs"

  # influxdb:
  #   image: influxdb:1.8
  #   ports:
  #     - 127.0.0.1:8086:8086
  #   volumes:
  #     - influxdb_data:/var/lib/influxdb
  #   environment:
  #     INFLUXDB_DB: ${INFLUXDB_NAME}
  #     INFLUXDB_ADMIN_USER: ${INFLUXDB_USER}
  #     INFLUXDB_ADMIN_PASSWORD: ${INFLUXDB_PASS}

  grafana:
    image: grafana/grafana:latest
    restart: unless-stopped
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/grafana-datasources.yml:/etc/grafana/provisioning/datasources/datasources.yaml
    environment:
      GF_SECURITY_ADMIN_USER: ${GF_SECURITY_ADMIN_USER}
      GF_SECURITY_ADMIN_PASSWORD: ${GF_SECURITY_ADMIN_PASSWORD}
      GF_INSTALL_PLUGINS: 'grafana-clock-panel,grafana-simple-json-datasource,grafana-worldmap-panel'
    ports:
      - 127.0.0.1:3060:3000
    labels:
      logging: "promtail"
      logging_jobname: "containerlogs"

  loki:
    image: grafana/loki:latest
    ports:
      - 127.0.0.1:3100:3100
    command: -config.file=/etc/loki/local-config.yaml
    labels:
      logging: "promtail"
      logging_jobname: "containerlogs"

  promtail:
    image:  grafana/promtail:latest
    container_name: promtail
    volumes:
      - ./promtail:/etc/promtail
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock
    command: -config.file=/etc/promtail/docker-config.yaml
    depends_on:
      - loki
    labels:
      logging: "promtail"
      logging_jobname: "containerlogs"

  # geoip2influx:
  #   image: gilbn/geoip2influx:latest
  #   environment:
  #     - PUID=1000
  #     - PGID=1000
  #     - TZ=America/Los_Angeles
  #     - INFLUX_HOST=${INFLUXDB_HOST}
  #     - INFLUX_HOST_PORT=${INFLUXDB_PORT}
  #     - MAXMINDDB_LICENSE_KEY=${MAXMINDDB_LICENSE_KEY}
  #   volumes:
  #     # - /path/to/appdata/geoip2influx:/config
  #     - nginx_data:/config/log/nginx/
  #   restart: unless-stopped

  # geoupdate:
  #   image: maxmindinc/geoipupdate:latest
  #   environment:
  #     - GEOIPUPDATE_ACCOUNT_ID=${GEOIPUPDATE_ACCOUNT_ID}
  #     - GEOIPUPDATE_LICENSE_KEY=${MAXMINDDB_LICENSE_KEY}
  #     - GEOIPUPDATE_EDITION_IDS=${GEOIPUPDATE_EDITION_IDS}
  #   volumes:
  #     - geoupdate_data:/usr/share/GeoIP
  #   restart: unless-stopped

volumes:
  db_data: {}
  redis_data: {}
  prometheus_data: {}
  grafana_data: {}
  # influxdb_data: {}
  # geoupdate_data: {}
  # nginx_data: {}