version: "3.9"

services:
  scheduler-scan:
    build:
      context: ./scheduler-scan
    environment:
      DB_USER: ${DJANGO_USER}
      DB_PASSWORD: ${DJANGO_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_DATABASE: ${DJANGO_DATABASE}
    volumes:
      - ./scheduler-scan:/app
    restart: unless-stopped

  scheduler-cleaner:
    build:
      context: ./scheduler-cleaner
    environment:
      DB_USER: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - ./scheduler-cleaner:/app
    restart: unless-stopped

  mailer:
    build:
      context: ./mailer
    environment:
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_USER: ${SMTP_USER}
      SMTP_PASS: ${SMTP_PASS}
      TARGET_URL: ${TARGET_URL}
    volumes:
      - ./mailer:/app
    restart: unless-stopped

  scanner:
    build:
      context: ./scanner
    environment:
      DB_USER: ${DJANGO_USER}
      DB_PASSWORD: ${DJANGO_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_DATABASE: ${DJANGO_DATABASE}
    volumes:
      - ./scanner:/app
    restart: unless-stopped

  cleaner:
    build:
      context: ./cleaner
    environment:
      DB_USER: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - ./cleaner:/app
    restart: unless-stopped

  redis:
    image: "redis:alpine"
    volumes:
      - redis_data:/data
    expose:
      - "6379"
    restart: unless-stopped

  redis-commander:
    image: rediscommander/redis-commander:latest
    hostname: redis-commander
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "127.0.0.1:8081:8081"
    restart: unless-stopped

  db:
    image: mysql:latest
    volumes:
      - db_data:/var/lib/mysql
      - ./db/backup:/docker-entrypoint-initdb.d
    restart: unless-stopped
    expose:
      - "3306"
    ports:
      - "127.0.0.1:3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  django:
    build:
      context: ./django
      dockerfile: Dockerfile.development
    environment:
      TARGET_URL: ${TARGET_URL}
      DB_HOST: ${DB_HOST}
      MYSQL_PORT: ${MYSQL_PORT}
      DJANGO_DATABASE: ${DJANGO_DATABASE}
      DJANGO_USER: ${DJANGO_USER}
      DJANGO_PASSWORD: ${DJANGO_PASSWORD}
      STRIPE_PUBLISHABLE_KEY: ${STRIPE_PUBLISHABLE_KEY}
      STRIPE_SECRET_KEY: ${STRIPE_SECRET_KEY}
      STRIPE_WEBHOOK_SECRET: ${STRIPE_WEBHOOK_SECRET}
    volumes:
      - ./django:/app
      - ./static:/app/static
    ports:
      - "127.0.0.1:8888:8888"
    expose:
      - "8888"
    depends_on:
      - db
    restart: unless-stopped

  wordpress:
    build:
      context: ./wordpress
    volumes:
      - ./wordpress/wp-config.php:/var/www/html/wp-config.php
      - ./wordpress/wp-content:/var/www/html/wp-content
    expose:
      - "80"
    ports:
      - "127.0.0.1:8000:80"
    environment:
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
      WORDPRESS_DEBUG: ${WORDPRESS_DEBUG}
      DOMAIN_NAME: ${DOMAIN_NAME}
      TARGET_URL: ${TARGET_URL}
    extra_hosts:
      - ${DOMAIN_NAME}:${PUBLIC_IP}
    depends_on:
      - db
      - redis
    restart: unless-stopped

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "127.0.0.1:3000:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/usr/src/app
    expose:
      - "8080"
    environment:
      CHOKIDAR_USEPOLLING: 'true'
      DOMAIN_NAME: ${DOMAIN_NAME}
      TARGET_URL: ${TARGET_URL}
      STRIPE_PUBLISHABLE_KEY: ${STRIPE_PUBLISHABLE_KEY}
    restart: unless-stopped

  nginx:
    image: openresty/openresty:latest
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./wordpress/wp-content:/var/www/html/wp-content
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
      - ./static:/static
    ports:
      - "80:80"
      - "443:443"
    environment:
      DOMAIN_NAME: ${DOMAIN_NAME}
      DOLLAR: ${DOLLAR}
    restart: unless-stopped
    command:
      [
        "/bin/sh",
        "-c",
        "echo hello world && envsubst < /etc/nginx/conf.d/nginx.conf.template > /etc/nginx/conf.d/nginx.conf && exec nginx -g 'daemon off;'"
      ]

  certbot:
    image: certbot/certbot:latest
    restart: unless-stopped
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

  prometheus:
    image: prom/prometheus:latest
    restart: unless-stopped
    volumes:
      - prometheus_data:/prometheus
      - ./prometheus/:/etc/prometheus/
    ports:
      - 127.0.0.1:9090:9090

  influxdb:
    image: influxdb:latest
    ports:
      - 127.0.0.1:8086:8086
    volumes:
      - influxdb-data:/var/lib/influxdb
    environment:
      INFLUXDB_DB: ${INFLUXDB_NAME}
      INFLUXDB_ADMIN_USER: ${INFLUXDB_USER}
      INFLUXDB_ADMIN_PASSWORD: ${INFLUXDB_PASS}

  grafana:
    image: grafana/grafana:6.5.2
    restart: unless-stopped
    volumes:
      - grafana_data:/var/lib/grafana
    ports:
      - 127.0.0.1:3060:3000
    environment:
      GF_INSTALL_PLUGINS: "grafana-clock-panel,grafana-simple-json-datasource"

volumes:
  db_data: {}
  redis_data: {}
  prometheus_data: {}
  grafana_data: {}
  influxdb-data: {}