# Generated by Django 4.2.2 on 2023-07-07 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='stripe_id',
            field=models.CharField(default='', max_length=100),
        ),
    ]
