# Generated by Django 3.2.20 on 2023-07-28 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stripeproduct',
            old_name='description',
            new_name='html',
        ),
    ]
