# Generated by Django 4.2.9 on 2024-02-16 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='ip',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scan',
            name='port',
            field=models.IntegerField(default=443),
            preserve_default=False,
        ),
    ]
