# Generated by Django 4.2.9 on 2024-02-16 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_scan_ip_scan_port'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scan',
            name='ip',
        ),
        migrations.AddField(
            model_name='scan',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scan',
            name='port',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
