# Generated by Django 3.2.20 on 2023-07-28 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_description_stripeproduct_html'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scan',
            old_name='last_scan',
            new_name='output',
        ),
    ]
