# Generated by Django 4.2.2 on 2023-07-07 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_account_stripe_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='stripe_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
