# Generated by Django 3.2.20 on 2023-07-28 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_last_scan_scan_output'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stripeproduct',
            name='created',
        ),
        migrations.RemoveField(
            model_name='stripeproduct',
            name='modified',
        ),
    ]
