# Generated by Django 4.2.9 on 2024-02-16 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_scan_alt_names_scan_common_name_scan_issuer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='error',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
