# Generated by Django 3.2.20 on 2023-08-11 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20230728_2040'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StripeProduct',
        ),
    ]
