# Generated by Django 3.2.20 on 2023-07-09 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_stripecustomer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StripeCustomer',
        ),
    ]
