# Generated by Django 3.2.20 on 2023-08-24 02:47

from django.db import migrations, models
import django_prometheus.models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_delete_stripeproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(default='hPWl5SOzXL65LOsVtFlTd9SnVs97LY7w', max_length=255)),
                ('last_seen', models.DateTimeField(default=None, null=True)),
            ],
            bases=(django_prometheus.models.ExportModelOperationsMixin('subscription'), models.Model),
        ),
    ]
