# Generated by Django 4.2.9 on 2024-02-17 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_scan_signature_algorithm'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='raw',
            field=models.TextField(null=True),
        ),
    ]
