# Generated by Django 3.2.20 on 2023-08-24 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_agent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='api_key',
            field=models.CharField(max_length=255),
        ),
    ]
