# Generated by Django 3.2.20 on 2023-07-17 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_snippet_stripecustomer_stripeproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='domain',
            name='last_scan',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='domain',
            name='port',
            field=models.IntegerField(blank=True),
        ),
    ]
