# Generated by Django 4.2.9 on 2024-02-17 21:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_scan_raw'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='activity',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
