# Generated by Django 3.2.20 on 2023-07-17 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20230717_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='last_scan',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='domain',
            name='port',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
