# Generated by Django 3.2.20 on 2023-08-24 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_agent_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='api_key',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
