# Generated by Django 3.2.20 on 2023-08-24 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_agent_api_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='name',
            field=models.CharField(default='lol', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='agent',
            name='api_key',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='last_seen',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
