# Generated by Django 3.2.20 on 2023-07-17 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20230717_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scan',
            name='domain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='api.domain'),
        ),
    ]
