# Generated by Django 3.2.20 on 2023-07-18 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_scan_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='scan_status',
            field=models.CharField(default='pending', max_length=100),
        ),
    ]
