# Generated by Django 4.2.9 on 2024-02-23 22:28

from django.db import migrations, models
import django_prometheus.models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_domain_last_scan_error_alter_domain_port_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanNow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_accessed', models.DateTimeField(blank=True, null=True)),
            ],
            bases=(django_prometheus.models.ExportModelOperationsMixin('scan'), models.Model),
        ),
    ]
