# Generated by Django 4.2.9 on 2024-02-24 22:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_prometheus.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0011_scannow'),
    ]

    operations = [
        migrations.AddField(
            model_name='scannow',
            name='domain',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.domain'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='EmailAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255)),
                ('verify_key', models.CharField(blank=True, max_length=255, null=True)),
                ('verified', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now=True)),
                ('verification_sent', models.DateTimeField(blank=True, null=True)),
                ('reset_key', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('reset_sent', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
                'unique_together': {('user', 'email')},
            },
            bases=(django_prometheus.models.ExportModelOperationsMixin('email_address'), models.Model),
        ),
    ]
