# Generated by Django 3.2.20 on 2023-08-24 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20230824_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='agent',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='agent', to='api.agent'),
        ),
    ]
