# Generated by Django 4.2.9 on 2024-02-25 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_scannow_domain_emailaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='scan_now_last_accessed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='ScanNow',
        ),
    ]
