# Generated by Django 4.2.9 on 2024-02-25 18:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_prometheus.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0014_emailaddress_domain'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('customer_id', models.CharField(default='', max_length=255)),
                ('client_reference_id', models.CharField(max_length=255)),
                ('subscription_id', models.CharField(default='', max_length=255)),
                ('subscription_type', models.CharField(choices=[('starter', 'Starter'), ('basic', 'Basic'), ('growth', 'Growth'), ('ultimate', 'Ultimate'), ('pending', 'Pending'), ('canceled', 'Canceled')], default='starter', max_length=255)),
                ('subscription_active', models.BooleanField(default=True)),
                ('period_start', models.DateTimeField(blank=True, default=None, null=True)),
                ('period_end', models.DateTimeField(blank=True, default=None, null=True)),
                ('previous_subscription_type', models.CharField(choices=[('starter', 'Starter'), ('basic', 'Basic'), ('growth', 'Growth'), ('ultimate', 'Ultimate'), ('pending', 'Pending'), ('canceled', 'Canceled')], default='starter', max_length=255)),
                ('cancel_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('cancel_at_period_end', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL)),
            ],
            bases=(django_prometheus.models.ExportModelOperationsMixin('subscription'), models.Model),
        ),
    ]
