# Generated by Django 3.2.20 on 2023-07-18 16:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20230718_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripecustomer',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stripecustomer',
            name='modified',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stripeproduct',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
