# Generated by Django 3.2.20 on 2023-07-18 18:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20230718_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scan',
            name='name',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
