# Generated by Django 3.2.20 on 2023-07-18 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_scan_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripecustomer',
            name='subscription_type',
            field=models.CharField(choices=[('starter', 'Starter'), ('basic', 'Basic'), ('growth', 'Growth'), ('ultimate', 'Ultimate')], default='starter', max_length=255),
        ),
    ]
