# Generated by Django 4.2.9 on 2024-02-25 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_remove_emailaddress_reset_key_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='emailaddress',
            unique_together=set(),
        ),
    ]
