# Generated by Django 3.2.20 on 2023-07-19 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_stripecustomer_subscription_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='ip_address',
            field=models.GenericIPAddressField(default=''),
        ),
        migrations.AlterField(
            model_name='domain',
            name='port',
            field=models.IntegerField(default=443),
        ),
    ]
