# Generated by Django 4.2.9 on 2024-02-27 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_notifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='daily',
            field=models.BooleanField(default=False),
        ),
    ]
