# Generated by Django 3.2.20 on 2023-07-19 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20230719_0350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='port',
            field=models.IntegerField(default=''),
        ),
    ]
