# Generated by Django 3.2.20 on 2023-07-19 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_domain_port'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='domain',
            name='port',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
