# Generated by Django 3.2.20 on 2023-07-19 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20230719_0353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scan',
            name='modified',
        ),
    ]
