# Generated by Django 3.2.20 on 2023-07-19 22:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_remove_scan_modified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scan',
            name='name',
        ),
        migrations.AddField(
            model_name='scan',
            name='uuid',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=255),
        ),
    ]
