# Generated by Django 3.2.20 on 2023-07-20 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_auto_20230719_2218'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Snippet',
        ),
    ]
