global:
  scrape_interval: 5s
  evaluation_interval: 5s
rule_files:
# - “first.rules”
# - “second.rules”
scrape_configs:
  - job_name: monitoring
    metrics_path: /monitor/metrics
    static_configs:
      - targets:
        - django:8888
  - job_name: node
    static_configs:
      - targets: 
        - 'node-exporter:9100'

remote_write:
  - url: "http://influxdb:8086/api/v1/prom/write?db=app"